# Generated by Django 3.0 on 2020-11-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicina',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_medicamento', models.CharField(choices=[('G', 'Generico'), ('C', 'Comercial')], max_length=12)),
            ],
        ),
    ]
